// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

#pragma once

#include <cstdint>
#include <string>

namespace whl {

/** Interface receiving state from the SDK. */
class StateListener {
public:
    virtual ~StateListener() {}

    /** Called back when a state request has been answered. */
    virtual void on_new_state(const std::string & name, int32_t value) = 0;
};

}  // namespace whl
