// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace whl {

class StateListener;
struct Configuration;

/** An instance of the sample SDK. */
class WasmHotLoading {
public:
    virtual ~WasmHotLoading() {}

    /** Create an instance using the provided configuration. */
    static std::shared_ptr<WasmHotLoading> create(const Configuration & configuration);

    /** Register a listener for state change events. */
    virtual void register_state_listener(const std::shared_ptr<StateListener> & listener) = 0;

    /** Trigger a query to be called back with the current state. */
    virtual void get_state() = 0;

    /** Update the SDK internal values. */
    virtual void update(const std::string & name, int32_t value) = 0;
};

}  // namespace whl
