// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

#include "state_listener.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace whl { namespace bridge {

StateListener::StateListener() : ::djinni::JniInterface<::whl::StateListener, StateListener>() {}

StateListener::~StateListener() = default;

StateListener::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

StateListener::JavaProxy::~JavaProxy() = default;

void StateListener::JavaProxy::on_new_state(const std::string & c_name, int32_t c_value) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::whl::bridge::StateListener>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onNewState,
                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c_name)),
                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c_value)));
    ::djinni::jniExceptionCheck(jniEnv);
}

} }  // namespace whl::bridge
