// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

package io.corendos.whl.bridge;

/** Interface receiving state from the SDK. */
public abstract class StateListener {
    /** Called back when a state request has been answered. */
    public abstract void onNewState(String name, int value);
}
