// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

#import <Foundation/Foundation.h>


/** Interface receiving state from the SDK. */
@interface StateListener : NSObject

/** Called back when a state request has been answered. */
- (void)onNewState:(nonnull NSString *)name
             value:(int32_t)value;

@end
