// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from whl.djinni

#import "Configuration.h"
#import <Foundation/Foundation.h>
@class StateListener;
@class WasmHotLoading;


/** An instance of the sample SDK. */
@interface WasmHotLoading : NSObject

/** Create an instance using the provided configuration. */
+ (nullable WasmHotLoading *)create:(nonnull Configuration *)configuration;

/** Register a listener for state change events. */
- (void)registerStateListener:(nullable StateListener *)listener;

/** Trigger a query to be called back with the current state. */
- (void)getState;

/** Update the SDK internal values. */
- (void)update:(nonnull NSString *)name
         value:(int32_t)value;

@end
